let evaluation_ratio_96 =[
    {
        "name":"幼年-男性",
        "count":20.99
    },
    {
        "name":"幼年-女性",
        "count":19.73
    },
    {
        "name":"青壯年-男性",
        "count":70.63
    },
    {
        "name":"青壯年-女性",
        "count":72.82
    },
    {
        "name":"老年-男性",
        "count":8.38
    },
    {
        "name":"老年-女性",
        "count":7.45
    }
];

let evaluation_ratio_101 =[
    {
        "name":"幼年-男性",
        "count":17.45
    },
    {
        "name":"幼年-女性",
        "count":16.14
    },
    {
        "name":"青壯年-男性",
        "count":74.09
    },
    {
        "name":"青壯年-女性",
        "count":75.16
    },
    {
        "name":"老年-男性",
        "count":8.46
    },
    {
        "name":"老年-女性",
        "count":8.7
    }
];

let evaluation_ratio_106 =[
    {
        "name":"幼年-男性",
        "count":15.87
    },
    {
        "name":"幼年-女性",
        "count":14.45
    },
    {
        "name":"青壯年-男性",
        "count":74.03
    },
    {
        "name":"青壯年-女性",
        "count":74.08
    },
    {
        "name":"老年-男性",
        "count":10.1
    },
    {
        "name":"老年-女性",
        "count":11.47
    }
];

let evaluation_ratio_111 =[
    {
        "name":"幼年-男性",
        "count":14.72
    },
    {
        "name":"幼年-女性",
        "count":13.32
    },
    {
        "name":"青壯年-男性",
        "count":72.19
    },
    {
        "name":"青壯年-女性",
        "count":71.24
    },
    {
        "name":"老年-男性",
        "count":13.09
    },
    {
        "name":"老年-女性",
        "count":15.44
    }
];

